class Moviestore{
    constructor(){
        this.movies = {};
        this.totalincome = 0;
     }
     
     addmovie(title , quantity ,priceperrental){
        if(this.movies[title]){
            this.movies[title].quantity +=quantity;
            console.log(`updated quantity for "${title}":${this.movies[title].quantity}copies now available.`);
        }else {
            this.movies[title] = {quantity , priceperrental ,rentedby:[]};

            console.log(`added "${title}" to the store with ${quantity} copies at $$ {priceperrental} per rental.`);
        }
        
     }
    }

    rent(movietitle, customername);{
        const movie = this.movies[moviestitle];
    if(!movie) {
        console.log(`sorry,"${movietitle}"is not available in the store.`);
        return;
    }
    if (movie.quantity > 0) {
        movie.quantity -=1;
        movie. rentedby.push(customername);
        this.totalincome += movie.priceperrental;
        console.log(`"${movietitle}" is currently out of stock, but it may become avaiable soon.`);

    }

    }

    checkavalability(movietitle);{
        const movie = this.movie[movietitle];
        if(!movie) {
            console.log(`"${movietitle}" is not available in the store.`);
        } else if (movie.quantity >0) {
            console.log(`"${movietitle}" is available with ${movie.quantity} copies in stock.`);

        } else {
            console.log(`"${movietitle}" is rented out but will be available soon.`);
        }
    }

    income();{
        console.log(`total income generated by the store is $${this.totalincome}.`);
    }